Hei, jeg la til noen nye elementer.
nadderud/mbube pull request #2
Opened 2019-10-26 21:36 UTC by MartinClementz

### Dette forslaget har to nye elementer
1. En ny side "bilder" hvor man kan se instagram bildene til gruppa. 
2. Footer'en er nå mye mindre, og informasjonen som tidligere var inni den, er nå flyttet til informasjon siden. + Informasjon om at gruppa eksisterer på sosiale medier.

2019-10-27 09:09 UTC, mgrim requested changes
Nice! 👏 Endringene ser bra ut! Sidene blir litt lettere, og det er bra. Det gir mening å samle info under info. Og bilder-siden er vakker, og kan hjelpe oss å huske å legge ut bilder på instagram.

Noen ting som må løses:
* [ ] Breakpoint for responsiv kollaps i topbar må settes til min 774px (ser ikke bra ut mellom 769-773px).
* [x] Vi bør være konsekvent om vi bruker npm eller yarn. (Vi kan ikke ha både package-lock.json og yarn.lock.)
* [ ] Vi bør fjerne utdaterte data og felt fra netlify-cms config (static/admin/config.yml). Det kan bli forvirrende i fremtiden, når vi ikke lenger husker hvordan ting henger sammen 🙄

2019-10-27 09:09 UTC, mgrim commented on src/components/Footer.jsx
>    >
Hele ```<Box>``` -komponenten kan fjernes her. (Den har ikke lenger noen funksjon uten pad, margin eller background.)

2019-10-27 09:09 UTC, mgrim commented on src/components/Footer.jsx
> +                <Link to="/info/" style={{color:"black"}}>mere informasjon</Link>
Typo
```suggestion
                <Link to="/info/" style={{color:"black"}}>mer informasjon</Link>
```

2019-10-27 09:09 UTC, mgrim commented on src/components/Footer.jsx
>  import { StaticQuery, graphql } from "gatsby"
```StaticQuery``` (og ```graphql```) kan fjernes. ```data```-propen brukes ikke lenger i ```Footer```.

2019-10-27 09:09 UTC, mgrim commented on src/components/Header.jsx
> +                    to: '/Instagram/',
Bør ikke url-en til bilder være ```'/bilder/'```?

2019-10-27 09:09 UTC, mgrim commented on src/pages/Instagram.js
> +                <p>Følg <strong>nadderudspeidergruppe</strong> på instagram for å se flere bilder.</p>
Foreslår at vi lenker til profilen.
```suggestion
                <p>Følg <a href="https://www.instagram.com/nadderudspeidergruppe/"><strong>nadderudspeidergruppe</strong> på Instagram</a> for å se flere bilder.</p>
```

2019-10-27 09:09 UTC, mgrim commented on src/pages/info.md
> +  926 11 925, mats@nadderud.no
```suggestion
  926 11 925, <a href="mailto:mats@nadderud.no">mats@nadderud.no</a>
```

2019-10-27 09:09 UTC, mgrim commented on src/pages/info.md
> +  411 44 182, mbhaukedal@gmail.com
```suggestion
  411 44 182, <a href="mailto:mbhaukedal@gmail.com">mbhaukedal@gmail.com</a>
```

2019-10-27 09:09 UTC, mgrim commented on src/pages/info.md
> +  977 97 439, janne.p.valkonen@gmail.com
```suggestion
  977 97 439, <a href="mailto:janne.p.valkonen@gmail.com">janne.p.valkonen@gmail.com</a>
```

2019-10-27 09:09 UTC, mgrim commented on src/pages/info.md
> +- Instagram: nadderudspeidergruppe
```suggestion
- Instagram: <a href="https://www.instagram.com/nadderudspeidergruppe/">nadderudspeidergruppe</a>
```

2019-10-27 09:09 UTC, mgrim commented on src/pages/info.md
> +- Facebook: Nadderud Speidergruppe
```suggestion
- Facebook: <a href="https://www.facebook.com/groups/248612515197643/">Nadderud speidergruppe</a>
```
Skal vi linke til denne, selv om det ikke er en offentlig profil?

2019-10-27 09:09 UTC, mgrim commented on src/components/Header.jsx
> +                  {
Foreslår at "Bilder" kommer før "Bli speider". 

Mener det er en fordel at "Bli speider" fungerer som en slags diskret call-to-action, hvis den står for seg selv.

2019-10-27 16:23 UTC, MartinClementz commented on src/pages/info.md
> +- Facebook: Nadderud Speidergruppe
Ja, jeg tror det er lurt. Da kan nye medlemmer fortere bli medlem av gruppa. Merete er jo også ganske aktiv på facebook siden.

2019-10-28 19:15 UTC, martcl reviewed
### Bilde fix
Jeg hadde noen problemer med å endre på bildene til `.md` sidene. Når jeg byttet navnet til et annet bilde i samme mappe, klarte siden ikke å laste inn bildet. Tror dette er fordi`.md` filene må referer til bildene relativt til posisjonen deres i directory-et. Derfor endret jeg hoved-markdown-sidene slik at de refererer til bildene relativt til posisjonen deres. Dette funket veldig bra for meg
Nå:
`image: ../../static/img/upload/sauejordet.jpg` 
Før:
`image: /img/upload/sauejordet.jpg`

Er dette slik du vil gjøre det? Eller finnes det en bedre måte?

### Header
**Må fikses**
- [ ] Breakpoint for responsiv kollaps I toppbar må endres

2019-11-03 05:56 UTC, mgrim commented
> Er dette slik du vil gjøre det? Eller finnes det en bedre måte?

Det finnes en bedre måte 😇 Pluginen ```gatsby-remark-relative-images``` skal egentlig ta seg av dette. Men jeg ser at vi bruker en utdatert versjon, som har noen kjente bugs. Prøv å oppdatere til 1.2.1 eller nyere.

2019-11-11 09:08 UTC, mgrim commented
@MartinClementz hvordan går det med denne? Hadde vært gøy å få merga snart.

2019-11-15 19:55 UTC, MartinClementz commented
Jeg kom bort i noen problemer når jeg skulle fikse problemet med `gatsby-remark-relative-images`.  Desuten fant jeg ikke versjonen som du refererte til `1.2.1`. Vi bruker nå `0.2.3` som i følge dokumentasjonen er den nyeste, men jeg prøvde med versjon `0.2.1` og `0.2.2`. Ingen av dem funket for meg :(

Jeg skal på Haslumseter tur i helgen, så jeg har ikke tid til å jobbe noe mere på en stund. Men det er bare å prøve å fikse problemet.

2019-11-15 21:55 UTC, MartinClementz commented
Bare glem det jeg fant ut av det! Jeg trengte kun å opdatere `"is-relative-url"` pakken, som er en pakke som `"gatsby-remark-relative-images"` må ha.

2019-11-16 07:00 UTC, mgrim approved these changes

2019-11-16 07:01 UTC, merged